"""Add documentation_html_s3_path

Revision ID: 0837c38e3292
Revises: 1d73be844b2a
Create Date: 2025-11-30 20:37:28.006771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0837c38e3292'
down_revision: Union[str, Sequence[str], None] = '1d73be844b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_specs', sa.Column('documentation_html_s3_path', sa.String(), nullable=True))
    op.alter_column('api_specs', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('api_specs', 'parsed_schema',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_specs', 'parsed_schema',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('api_specs', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('api_specs', 'documentation_html_s3_path')
    # ### end Alembic commands ###
