"""create tenants table

Revision ID: 240e588bf0f8
Revises: 0837c38e3292
Create Date: 2025-12-03 08:46:12.982901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240e588bf0f8'
down_revision: Union[str, Sequence[str], None] = '0837c38e3292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_api_specs_id'), 'api_specs', ['id'], unique=False)
    op.alter_column('documentation_artifacts', 'api_spec_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_documentation_artifacts_id'), 'documentation_artifacts', ['id'], unique=False)
    op.drop_constraint(op.f('documentation_artifacts_api_spec_id_fkey'), 'documentation_artifacts', type_='foreignkey')
    op.create_foreign_key(None, 'documentation_artifacts', 'api_specs', ['api_spec_id'], ['id'])
    op.alter_column('generation_jobs', 'api_spec_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_generation_jobs_id'), 'generation_jobs', ['id'], unique=False)
    op.drop_constraint(op.f('generation_jobs_api_spec_id_fkey'), 'generation_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'generation_jobs', 'api_specs', ['api_spec_id'], ['id'])
    op.alter_column('version_history', 'api_spec_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_version_history_id'), 'version_history', ['id'], unique=False)
    op.drop_constraint(op.f('version_history_api_spec_id_fkey'), 'version_history', type_='foreignkey')
    op.create_foreign_key(None, 'version_history', 'api_specs', ['api_spec_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'version_history', type_='foreignkey')
    op.create_foreign_key(op.f('version_history_api_spec_id_fkey'), 'version_history', 'api_specs', ['api_spec_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_version_history_id'), table_name='version_history')
    op.alter_column('version_history', 'api_spec_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('generation_jobs_api_spec_id_fkey'), 'generation_jobs', 'api_specs', ['api_spec_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_generation_jobs_id'), table_name='generation_jobs')
    op.alter_column('generation_jobs', 'api_spec_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'documentation_artifacts', type_='foreignkey')
    op.create_foreign_key(op.f('documentation_artifacts_api_spec_id_fkey'), 'documentation_artifacts', 'api_specs', ['api_spec_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_documentation_artifacts_id'), table_name='documentation_artifacts')
    op.alter_column('documentation_artifacts', 'api_spec_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_api_specs_id'), table_name='api_specs')
    op.drop_table('tenants')
    # ### end Alembic commands ###
