"""add version column to documentation_artifacts

Revision ID: 3244ecebfdf5
Revises: b809b5959ecf
Create Date: 2025-12-21 22:10:28.141534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3244ecebfdf5'
down_revision: Union[str, Sequence[str], None] = 'b809b5959ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_specs_id'), 'api_specs', ['id'], unique=False)
    op.create_index(op.f('ix_documentation_artifacts_api_spec_id'), 'documentation_artifacts', ['api_spec_id'], unique=False)
    op.drop_constraint(op.f('fk_documentation_artifacts_api_spec'), 'documentation_artifacts', type_='foreignkey')
    op.create_foreign_key(None, 'documentation_artifacts', 'api_specs', ['api_spec_id'], ['id'])
    op.alter_column('generation_jobs', 'api_spec_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('fk_generation_jobs_api_spec'), 'generation_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'generation_jobs', 'api_specs', ['api_spec_id'], ['id'])
    op.alter_column('version_history', 'api_spec_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_version_history_id'), 'version_history', ['id'], unique=False)
    op.drop_constraint(op.f('fk_version_history_api_spec'), 'version_history', type_='foreignkey')
    op.create_foreign_key(None, 'version_history', 'api_specs', ['api_spec_id'], ['id'])
    op.drop_index(op.f('ix_watched_apis_polling_enabled'), table_name='watched_apis')
    op.drop_index(op.f('ix_watched_apis_status'), table_name='watched_apis')
    op.drop_index(op.f('ix_watched_apis_tenant_id'), table_name='watched_apis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_watched_apis_tenant_id'), 'watched_apis', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_watched_apis_status'), 'watched_apis', ['status'], unique=False)
    op.create_index(op.f('ix_watched_apis_polling_enabled'), 'watched_apis', ['polling_enabled'], unique=False)
    op.drop_constraint(None, 'version_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_version_history_api_spec'), 'version_history', 'api_specs', ['api_spec_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_version_history_id'), table_name='version_history')
    op.alter_column('version_history', 'api_spec_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_generation_jobs_api_spec'), 'generation_jobs', 'api_specs', ['api_spec_id'], ['id'], ondelete='CASCADE')
    op.alter_column('generation_jobs', 'api_spec_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'documentation_artifacts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documentation_artifacts_api_spec'), 'documentation_artifacts', 'api_specs', ['api_spec_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_documentation_artifacts_api_spec_id'), table_name='documentation_artifacts')
    op.drop_index(op.f('ix_api_specs_id'), table_name='api_specs')
    # ### end Alembic commands ###
