"""Initial schema with audit columns and string tenant IDs

Revision ID: 48f3d6547f8b
Revises: 
Create Date: 2025-12-29 18:12:34.068696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48f3d6547f8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable UUID extension
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    op.create_table('tenants',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('providers',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_providers_tenant_slug')
    )
    op.create_table('api_products',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'slug', name='uq_api_products_provider_slug')
    )
    op.create_index(op.f('ix_api_products_provider_id'), 'api_products', ['provider_id'], unique=False)
    op.create_table('api_specs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('api_product_id', sa.UUID(), nullable=True),
    sa.Column('api_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('original_file_s3_path', sa.String(), nullable=False),
    sa.Column('documentation_html_s3_path', sa.String(), nullable=True),
    sa.Column('parsed_schema', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'),
    sa.ForeignKeyConstraint(['api_product_id'], ['api_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider_id', 'api_name', 'version', name='uq_api_specs_provider_api_version')
    )
    op.create_index(op.f('ix_api_specs_api_product_id'), 'api_specs', ['api_product_id'], unique=False)
    op.create_index(op.f('ix_api_specs_provider_id'), 'api_specs', ['provider_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_spec_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('output_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['api_spec_id'], ['api_specs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_api_spec_id'), 'generation_jobs', ['api_spec_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_id'), 'generation_jobs', ['id'], unique=False)
    op.create_table('version_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_spec_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('diff', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('changelog', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'),
    sa.ForeignKeyConstraint(['api_spec_id'], ['api_specs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_version_history_api_spec_id'), 'version_history', ['api_spec_id'], unique=False)
    op.create_index(op.f('ix_version_history_id'), 'version_history', ['id'], unique=False)
    op.create_table('watched_apis',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('api_product_id', sa.UUID(), nullable=False),
    sa.Column('api_spec_id', sa.UUID(), nullable=True),
    sa.Column('spec_url', sa.String(), nullable=False),
    sa.Column('spec_format', sa.String(), nullable=True),
    sa.Column('polling_frequency', sa.String(), nullable=False),
    sa.Column('polling_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_version_detected', sa.Integer(), nullable=True),
    sa.Column('last_spec_hash', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'),
    sa.ForeignKeyConstraint(['api_product_id'], ['api_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['api_spec_id'], ['api_specs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watched_apis_api_product_id'), 'watched_apis', ['api_product_id'], unique=False)
    op.create_index(op.f('ix_watched_apis_api_spec_id'), 'watched_apis', ['api_spec_id'], unique=False)
    op.create_index(op.f('ix_watched_apis_provider_id'), 'watched_apis', ['provider_id'], unique=False)
    op.create_table('alert_configurations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('watched_api_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('alert_on_breaking_changes', sa.Boolean(), nullable=False),
    sa.Column('alert_on_non_breaking_changes', sa.Boolean(), nullable=False),
    sa.Column('alert_on_endpoint_failures', sa.Boolean(), nullable=False),
    sa.Column('alert_on_endpoint_recovery', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['watched_api_id'], ['watched_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_configurations_watched_api_id'), 'alert_configurations', ['watched_api_id'], unique=False)
    op.create_table('documentation_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_spec_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('version_history_id', sa.Integer(), nullable=True),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('s3_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'),
    sa.ForeignKeyConstraint(['api_spec_id'], ['api_specs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['version_history_id'], ['version_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentation_artifacts_api_spec_id'), 'documentation_artifacts', ['api_spec_id'], unique=False)
    op.create_index(op.f('ix_documentation_artifacts_id'), 'documentation_artifacts', ['id'], unique=False)
    op.create_table('endpoint_health',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('watched_api_id', sa.UUID(), nullable=False),
    sa.Column('endpoint_path', sa.String(), nullable=False),
    sa.Column('http_method', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'),
    sa.ForeignKeyConstraint(['watched_api_id'], ['watched_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_health_watched_api_id'), 'endpoint_health', ['watched_api_id'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('watched_api_id', sa.UUID(), nullable=False),
    sa.Column('alert_config_id', sa.UUID(), nullable=False),
    sa.Column('version_history_id', sa.Integer(), nullable=True),
    sa.Column('alert_reason', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('endpoint_path', sa.String(), nullable=True),
    sa.Column('http_method', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'),
    sa.ForeignKeyConstraint(['alert_config_id'], ['alert_configurations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['version_history_id'], ['version_history.id'], ),
    sa.ForeignKeyConstraint(['watched_api_id'], ['watched_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_alert_config_id'), 'alert_history', ['alert_config_id'], unique=False)
    op.create_index(op.f('ix_alert_history_watched_api_id'), 'alert_history', ['watched_api_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_history_watched_api_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_alert_config_id'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_endpoint_health_watched_api_id'), table_name='endpoint_health')
    op.drop_table('endpoint_health')
    op.drop_index(op.f('ix_documentation_artifacts_id'), table_name='documentation_artifacts')
    op.drop_index(op.f('ix_documentation_artifacts_api_spec_id'), table_name='documentation_artifacts')
    op.drop_table('documentation_artifacts')
    op.drop_index(op.f('ix_alert_configurations_watched_api_id'), table_name='alert_configurations')
    op.drop_table('alert_configurations')
    op.drop_index(op.f('ix_watched_apis_provider_id'), table_name='watched_apis')
    op.drop_index(op.f('ix_watched_apis_api_spec_id'), table_name='watched_apis')
    op.drop_index(op.f('ix_watched_apis_api_product_id'), table_name='watched_apis')
    op.drop_table('watched_apis')
    op.drop_index(op.f('ix_version_history_id'), table_name='version_history')
    op.drop_index(op.f('ix_version_history_api_spec_id'), table_name='version_history')
    op.drop_table('version_history')
    op.drop_index(op.f('ix_generation_jobs_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_api_spec_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_api_specs_provider_id'), table_name='api_specs')
    op.drop_index(op.f('ix_api_specs_api_product_id'), table_name='api_specs')
    op.drop_table('api_specs')
    op.drop_index(op.f('ix_api_products_provider_id'), table_name='api_products')
    op.drop_table('api_products')
    op.drop_table('providers')
    op.drop_table('tenants')
    # ### end Alembic commands ###
