"""add website, logo_url, and description to providers

Revision ID: 51b7984f5b27
Revises: c77ca0aa40b0
Create Date: 2026-01-01 15:35:30.759560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b7984f5b27'
down_revision: Union[str, Sequence[str], None] = 'c77ca0aa40b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('website', sa.String(length=500), nullable=True))
    op.add_column('providers', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('providers', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'description')
    op.drop_column('providers', 'logo_url')
    op.drop_column('providers', 'website')
    # ### end Alembic commands ###
