"""add organization members and invitations

Revision ID: 533bbfa38cd0
Revises: eb48c827bee1
Create Date: 2026-01-14 14:10:02.822285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '533bbfa38cd0'
down_revision: Union[str, Sequence[str], None] = 'eb48c827bee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=255), nullable=False),
    sa.Column('invited_by_name', sa.String(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_invitations_email_status', 'organization_invitations', ['email', 'status'], unique=False)
    op.create_index('ix_org_invitations_tenant_status', 'organization_invitations', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_organization_invitations_email'), 'organization_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invitations_tenant_id'), 'organization_invitations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_token'), 'organization_invitations', ['token'], unique=True)
    op.create_table('organization_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('invited_by_user_id', sa.String(length=255), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_members_status', 'organization_members', ['status'], unique=False)
    op.create_index('ix_org_members_tenant_user', 'organization_members', ['tenant_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_organization_members_tenant_id'), 'organization_members', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.alter_column('affected_code_usages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp when record was created',
               existing_nullable=False)
    op.alter_column('affected_code_usages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='UTC timestamp when record was last updated')
    op.alter_column('affected_code_usages', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Clerk user_id of user who created this record',
               existing_nullable=True)
    op.alter_column('affected_code_usages', 'updated_by_user_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Clerk user_id of user who last updated this record',
               existing_nullable=True)
    op.add_column('tenants', sa.Column('owner_user_id', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # DATA MIGRATION: Backfill organization_members for existing tenants
    # This ensures all existing users have membership records
    connection = op.get_bind()
    
    # Get all existing tenants
    result = connection.execute(sa.text("""
        SELECT id, created_by_user_id, is_organization 
        FROM tenants 
        WHERE status = 'active'
    """))
    
    for tenant_id, created_by_user_id, is_organization in result:
        # Determine the user_id for this tenant
        if is_organization:
            # For organization tenants, tenant_id is the org_id (not a user_id)
            # We'll use created_by_user_id if available, otherwise skip
            if created_by_user_id:
                user_id = created_by_user_id
            else:
                # Skip if no creator info (shouldn't happen, but be safe)
                continue
        else:
            # For personal tenants, tenant_id IS the user_id
            user_id = tenant_id
        
        # Set owner_user_id for this tenant
        connection.execute(sa.text("""
            UPDATE tenants 
            SET owner_user_id = :user_id 
            WHERE id = :tenant_id
        """), {"user_id": user_id, "tenant_id": tenant_id})
        
        # Create organization_member record for this user
        connection.execute(sa.text("""
            INSERT INTO organization_members 
            (id, tenant_id, user_id, role, status, joined_at, created_at)
            VALUES (gen_random_uuid(), :tenant_id, :user_id, 'owner', 'active', NOW(), NOW())
            ON CONFLICT (tenant_id, user_id) DO NOTHING
        """), {"tenant_id": tenant_id, "user_id": user_id})
        
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'settings')
    op.drop_column('tenants', 'owner_user_id')
    op.alter_column('affected_code_usages', 'updated_by_user_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Clerk user_id of user who last updated this record',
               existing_nullable=True)
    op.alter_column('affected_code_usages', 'created_by_user_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Clerk user_id of user who created this record',
               existing_nullable=True)
    op.alter_column('affected_code_usages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment=None,
               existing_comment='UTC timestamp when record was last updated')
    op.alter_column('affected_code_usages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='UTC timestamp when record was created',
               existing_nullable=False)
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_tenant_id'), table_name='organization_members')
    op.drop_index('ix_org_members_tenant_user', table_name='organization_members')
    op.drop_index('ix_org_members_status', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organization_invitations_token'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_tenant_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_email'), table_name='organization_invitations')
    op.drop_index('ix_org_invitations_tenant_status', table_name='organization_invitations')
    op.drop_index('ix_org_invitations_email_status', table_name='organization_invitations')
    op.drop_table('organization_invitations')
    # ### end Alembic commands ###
