"""add audit columns to generation_jobs and create code repositories tables

Revision ID: 582bfa228ab8
Revises: 5fd413398818
Create Date: 2026-01-05 09:15:46.825303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '582bfa228ab8'
down_revision: Union[str, Sequence[str], None] = '5fd413398818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_repositories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('github_installation_id', sa.String(length=100), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('owner_team', sa.String(length=255), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_commit_sha', sa.String(length=40), nullable=True),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('last_scan_error', sa.Text(), nullable=True),
    sa.Column('total_files_scanned', sa.Integer(), nullable=False),
    sa.Column('total_endpoints_found', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_code_repositories_scan_status', 'code_repositories', ['scan_status'], unique=False)
    op.create_index(op.f('ix_code_repositories_tenant_id'), 'code_repositories', ['tenant_id'], unique=False)
    op.create_table('code_repo_endpoint_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_repository_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('endpoint_path', sa.String(length=500), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('code_context', sa.Text(), nullable=True),
    sa.Column('detection_method', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['code_repository_id'], ['code_repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_code_repo_endpoint_usages_code_repository_id', 'code_repo_endpoint_usages', ['code_repository_id'], unique=False)
    op.create_index('ix_code_repo_endpoint_usages_endpoint_path', 'code_repo_endpoint_usages', ['endpoint_path'], unique=False)
    op.create_index('ix_code_repo_endpoint_usages_lookup', 'code_repo_endpoint_usages', ['tenant_id', 'endpoint_path', 'http_method'], unique=False)
    op.create_index('ix_code_repo_endpoint_usages_tenant_id', 'code_repo_endpoint_usages', ['tenant_id'], unique=False)
    op.add_column('generation_jobs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'))
    op.add_column('generation_jobs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'))
    op.add_column('generation_jobs', sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'))
    op.add_column('generation_jobs', sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_jobs', 'updated_by_user_id')
    op.drop_column('generation_jobs', 'created_by_user_id')
    op.drop_column('generation_jobs', 'updated_at')
    op.drop_column('generation_jobs', 'created_at')
    op.drop_index('ix_code_repo_endpoint_usages_tenant_id', table_name='code_repo_endpoint_usages')
    op.drop_index('ix_code_repo_endpoint_usages_lookup', table_name='code_repo_endpoint_usages')
    op.drop_index('ix_code_repo_endpoint_usages_endpoint_path', table_name='code_repo_endpoint_usages')
    op.drop_index('ix_code_repo_endpoint_usages_code_repository_id', table_name='code_repo_endpoint_usages')
    op.drop_table('code_repo_endpoint_usages')
    op.drop_index(op.f('ix_code_repositories_tenant_id'), table_name='code_repositories')
    op.drop_index('ix_code_repositories_scan_status', table_name='code_repositories')
    op.drop_table('code_repositories')
    # ### end Alembic commands ###
