"""add tenant_id to all tables

Revision ID: 5ed13436ca15
Revises: c969345a1d15
Create Date: 2025-12-03 11:32:27.636352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed13436ca15'
down_revision: Union[str, Sequence[str], None] = 'c969345a1d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_specs', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'api_specs', 'tenants', ['tenant_id'], ['id'])
    op.add_column('documentation_artifacts', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documentation_artifacts', 'tenants', ['tenant_id'], ['id'])
    op.add_column('version_history', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'version_history', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'version_history', type_='foreignkey')
    op.drop_column('version_history', 'tenant_id')
    op.drop_constraint(None, 'documentation_artifacts', type_='foreignkey')
    op.drop_column('documentation_artifacts', 'tenant_id')
    op.drop_constraint(None, 'api_specs', type_='foreignkey')
    op.drop_column('api_specs', 'tenant_id')
    # ### end Alembic commands ###
