"""add status to api_products

Revision ID: 5fd413398818
Revises: fd791c1f1f6c
Create Date: 2026-01-02 20:01:41.919260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd413398818'
down_revision: Union[str, Sequence[str], None] = 'fd791c1f1f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_products', sa.Column('status', sa.String(), server_default='active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_products', 'status')
    # ### end Alembic commands ###
