"""add provider_id and api_name to api_specs

Revision ID: 64b7882daf80
Revises: 01dc3844490a
Create Date: 2025-12-05 16:39:45.820705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b7882daf80'
down_revision: Union[str, Sequence[str], None] = '01dc3844490a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_specs', sa.Column('provider_id', sa.UUID(), nullable=True))
    op.add_column('api_specs', sa.Column('api_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_specs', 'api_name')
    op.drop_column('api_specs', 'provider_id')
    # ### end Alembic commands ###
