"""add watched_apis table for Phase 4A

Revision ID: b809b5959ecf
Revises: f291ba9c9332
Create Date: 2025-12-21 20:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b809b5959ecf'
down_revision: Union[str, Sequence[str], None] = 'f291ba9c9332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watched_apis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('api_product_id', sa.UUID(), nullable=False),
    sa.Column('spec_url', sa.String(), nullable=False),
    sa.Column('spec_format', sa.String(), nullable=True),
    sa.Column('polling_frequency', sa.String(), server_default='daily', nullable=False),
    sa.Column('polling_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_version_detected', sa.Integer(), nullable=True),
    sa.Column('last_spec_hash', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_product_id'], ['api_products.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watched_apis_polling_enabled'), 'watched_apis', ['polling_enabled'], unique=False)
    op.create_index(op.f('ix_watched_apis_status'), 'watched_apis', ['status'], unique=False)
    op.create_index(op.f('ix_watched_apis_tenant_id'), 'watched_apis', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watched_apis_tenant_id'), table_name='watched_apis')
    op.drop_index(op.f('ix_watched_apis_status'), table_name='watched_apis')
    op.drop_index(op.f('ix_watched_apis_polling_enabled'), table_name='watched_apis')
    op.drop_table('watched_apis')
    # ### end Alembic commands ###