"""Add is_organization to tenants

Revision ID: c77ca0aa40b0
Revises: 48f3d6547f8b
Create Date: 2025-12-29 18:43:56.460936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77ca0aa40b0'
down_revision: Union[str, Sequence[str], None] = '48f3d6547f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_organization', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'is_organization')
    # ### end Alembic commands ###
