"""add tenant_id columns

Revision ID: c969345a1d15
Revises: 240e588bf0f8
Create Date: 2025-12-03 08:51:40.814560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c969345a1d15'
down_revision: Union[str, Sequence[str], None] = '240e588bf0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'generation_jobs', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generation_jobs', type_='foreignkey')
    op.drop_column('generation_jobs', 'tenant_id')
    # ### end Alembic commands ###
