"""add automatic scanning columns to code repositories

Revision ID: e28f119821bf
Revises: 533bbfa38cd0
Create Date: 2026-01-15 07:05:34.553327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28f119821bf'
down_revision: Union[str, Sequence[str], None] = '533bbfa38cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add columns as NULLABLE first
    op.add_column('code_repositories', sa.Column('scan_interval_hours', sa.Integer(), nullable=True))
    op.add_column('code_repositories', sa.Column('next_scan_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('code_repositories', sa.Column('consecutive_scan_failures', sa.Integer(), nullable=True))
    
    # Step 2: Set default values for existing rows
    connection = op.get_bind()
    
    # Update existing repositories to scan within next 24 hours
    # Spread them out randomly to avoid all scanning at once
    connection.execute(sa.text("""
        UPDATE code_repositories 
        SET 
            scan_interval_hours = 24,
            consecutive_scan_failures = 0,
            next_scan_at = NOW() + (random() * INTERVAL '24 hours')
        WHERE scan_interval_hours IS NULL
    """))
    
    # Step 3: Make columns NOT NULL now that they have values
    op.alter_column('code_repositories', 'scan_interval_hours', nullable=False)
    op.alter_column('code_repositories', 'consecutive_scan_failures', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_repositories', 'consecutive_scan_failures')
    op.drop_column('code_repositories', 'next_scan_at')
    op.drop_column('code_repositories', 'scan_interval_hours')
    # ### end Alembic commands ###
