"""add impact analysis tables

Revision ID: eb48c827bee1
Revises: f30455b6d7d8
Create Date: 2026-01-10 20:14:59.325935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb48c827bee1'
down_revision: Union[str, Sequence[str], None] = 'f30455b6d7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_analysis_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('spec_id', sa.UUID(), nullable=False),
    sa.Column('version_history_id', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('has_impact', sa.Boolean(), nullable=False),
    sa.Column('total_breaking_changes', sa.Integer(), nullable=False),
    sa.Column('total_affected_repos', sa.Integer(), nullable=False),
    sa.Column('total_usages_affected', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when record was last updated'),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who created this record'),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True, comment='Clerk user_id of user who last updated this record'),
    sa.ForeignKeyConstraint(['spec_id'], ['api_specs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_history_id'], ['version_history.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_impact_analyzed_at', 'impact_analysis_results', ['analyzed_at'], unique=False)
    op.create_index('idx_impact_tenant_spec', 'impact_analysis_results', ['tenant_id', 'spec_id'], unique=False)
    op.create_index('idx_impact_version', 'impact_analysis_results', ['version_history_id'], unique=False)
    op.create_index(op.f('ix_impact_analysis_results_spec_id'), 'impact_analysis_results', ['spec_id'], unique=False)
    op.create_index(op.f('ix_impact_analysis_results_tenant_id'), 'impact_analysis_results', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_impact_analysis_results_version_history_id'), 'impact_analysis_results', ['version_history_id'], unique=False)
    op.create_table('affected_code_usages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('impact_analysis_result_id', sa.Uuid(), nullable=False),
    sa.Column('code_repo_endpoint_usage_id', sa.Integer(), nullable=False),
    sa.Column('breaking_change_type', sa.String(length=50), nullable=False),
    sa.Column('endpoint_path', sa.String(length=500), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('code_context', sa.Text(), nullable=False),
    sa.Column('repository_name', sa.String(length=255), nullable=False),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=255), nullable=True),
    sa.Column('updated_by_user_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['code_repo_endpoint_usage_id'], ['code_repo_endpoint_usages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['impact_analysis_result_id'], ['impact_analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_affected_impact', 'affected_code_usages', ['impact_analysis_result_id'], unique=False)
    op.create_index('idx_affected_tenant_endpoint', 'affected_code_usages', ['tenant_id', 'endpoint_path'], unique=False)
    op.create_index('idx_affected_usage', 'affected_code_usages', ['code_repo_endpoint_usage_id'], unique=False)
    op.create_index(op.f('ix_affected_code_usages_breaking_change_type'), 'affected_code_usages', ['breaking_change_type'], unique=False)
    op.create_index(op.f('ix_affected_code_usages_code_repo_endpoint_usage_id'), 'affected_code_usages', ['code_repo_endpoint_usage_id'], unique=False)
    op.create_index(op.f('ix_affected_code_usages_impact_analysis_result_id'), 'affected_code_usages', ['impact_analysis_result_id'], unique=False)
    op.create_index(op.f('ix_affected_code_usages_tenant_id'), 'affected_code_usages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affected_code_usages_tenant_id'), table_name='affected_code_usages')
    op.drop_index(op.f('ix_affected_code_usages_impact_analysis_result_id'), table_name='affected_code_usages')
    op.drop_index(op.f('ix_affected_code_usages_code_repo_endpoint_usage_id'), table_name='affected_code_usages')
    op.drop_index(op.f('ix_affected_code_usages_breaking_change_type'), table_name='affected_code_usages')
    op.drop_index('idx_affected_usage', table_name='affected_code_usages')
    op.drop_index('idx_affected_tenant_endpoint', table_name='affected_code_usages')
    op.drop_index('idx_affected_impact', table_name='affected_code_usages')
    op.drop_table('affected_code_usages')
    op.drop_index(op.f('ix_impact_analysis_results_version_history_id'), table_name='impact_analysis_results')
    op.drop_index(op.f('ix_impact_analysis_results_tenant_id'), table_name='impact_analysis_results')
    op.drop_index(op.f('ix_impact_analysis_results_spec_id'), table_name='impact_analysis_results')
    op.drop_index('idx_impact_version', table_name='impact_analysis_results')
    op.drop_index('idx_impact_tenant_spec', table_name='impact_analysis_results')
    op.drop_index('idx_impact_analyzed_at', table_name='impact_analysis_results')
    op.drop_table('impact_analysis_results')
    # ### end Alembic commands ###
