"""add description to api_products.

Revision ID: fd791c1f1f6c
Revises: 51b7984f5b27
Create Date: 2026-01-01 20:34:04.801720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd791c1f1f6c'
down_revision: Union[str, Sequence[str], None] = '51b7984f5b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_products', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_products', 'description')
    # ### end Alembic commands ###
